### PR TITLE
Improve stackoverflow

### PR DESCRIPTION
**Pull request by ClaudioESSilva**
Improve Stackoverflow startup time.

- Remove move of existing ldf (from 7zp)
- Added `ATTACH_REBUILD_LOG` to the SQL script

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Looks good, even if the performance isn't what we hoped 💯

**Comment by ClaudioESSilva** [comment]
It went from +10min to 2min it's awesome already 🤗

**Comment by potatoqualitee** [comment]
haha wait, i thought it was still the same-ish! Great news! My bad 🤗

**Comment by ClaudioESSilva** [comment]
At least comparing our sql server error log for the before/after

**Pull request merged**
